---
- name: all PIs
  hosts: all
  vars_files:
    - vars/common.yaml
    - "vars/{{ hostname }}.yaml"
  vars:
    install_updates: false

  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        state: latest
        update_cache: true
        # upgrade: full
      when: install_updates
    - name: install some packages
      ansible.builtin.package:
        update_cache: yes
        name:
          - vim
          - python3-pip
        state: latest
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
    - name: SSH server
      ansible.builtin.include_tasks: ssh.yaml
    - name: Set Password
      ansible.builtin.include_tasks: password.yaml
    - name: WiFi
      ansible.builtin.include_tasks: wifi.yaml
    - name: tinc
      ansible.builtin.include_tasks: tinc.yaml
    - name: set timezone
      ansible.builtin.file:
        src: /usr/share/zoneinfo/Europe/Berlin
        dest: /etc/localtime
        state: link
        force: yes
    - name: activate alias ll
      ansible.builtin.replace:
        path: /home/pi/.bashrc
        regexp: "^#alias ll='ls -l'"
        replace: "alias ll='ls -l'"
