---
- name: set password
  ansible.builtin.user:
    name: pi
    password: "{{ pi_user_password | trim | string | password_hash('sha512') }}"
- name: add userconf.txt
  ansible.builtin.copy:
    content: |
      pi:{{ pi_user_password | trim | string | password_hash('sha512') }}
    dest: "/boot/userconf.txt"
